JXGw:
  dt: 0.005
  decimation: 4
  fixed_kp: [160.0, 160.0, 160.0, 0.0,
             160.0, 160.0, 160.0, 0.0,
             160.0, 160.0, 160.0, 0.0,
             160.0, 160.0, 160.0, 0.0]
  fixed_kd: [1.0, 1.0, 1.0, 0.5,
             1.0, 1.0, 1.0, 0.5,
             1.0, 1.0, 1.0, 0.5,
             1.0, 1.0, 1.0, 0.5]
  num_of_dofs: 16
  wheel_indices: [3, 7, 11, 15]
  torque_limits: [60.0, 60.0, 120.0, 17.0,
                  60.0, 60.0, 120.0, 17.0,
                  60.0, 60.0, 120.0, 17.0,
                  60.0, 60.0, 120.0, 17.0]
  default_dof_pos: [0.0, -0.55, 1.68, 0.0,
                    0.0, -0.55, 1.68, 0.0,
                    0.0, 0.55, -1.68, 0.0,
                    0.0, 0.55, -1.68, 0.0]
  lying_down_offset: [  0.0, 0.0, 0.0, 0.0,
                        0.0, 0.0, 0.0, 0.0,
                        0.0, 0.0, 0.0, 0.0,
                        0.0, 0.0, 0.0, 0.0]
  joint_names: ["FL_hip_joint", "FL_thigh_joint", "FL_calf_joint", "FL_foot_joint",
                "FR_hip_joint", "FR_thigh_joint", "FR_calf_joint", "FR_foot_joint",
                "RL_hip_joint", "RL_thigh_joint", "RL_calf_joint", "RL_foot_joint",
                "RR_hip_joint", "RR_thigh_joint", "RR_calf_joint", "RR_foot_joint"]
  joint_controller_names: ["FL_hip_controller", "FL_thigh_controller", "FL_calf_controller", "FL_foot_controller",
                           "FR_hip_controller", "FR_thigh_controller", "FR_calf_controller", "FR_foot_controller",
                           "RL_hip_controller", "RL_thigh_controller", "RL_calf_controller", "RL_foot_controller",
                           "RR_hip_controller", "RR_thigh_controller", "RR_calf_controller", "RR_foot_controller"]
  joint_mapping: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
